name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        GPIO_ONLY: [false, true]
        LOG_ON_GP01: [false, true]
    uses: ./.github/workflows/build.yml
    with:
      GPIO_ONLY: ${{ matrix.GPIO_ONLY }}
      LOG_ON_GP01: ${{ matrix.LOG_ON_GP01 }}
